### ISSUE TITLE
Padding missing when user list scrolls.

### ISSUE THREAD

**Issue by jakehamilton** [jakehamilton/scrumfi.sh#1]
The padding in the user list is missing at the bottom when content overflows.

![image](https://user-images.githubusercontent.com/7005773/95392094-04555e00-08ad-11eb-9808-ebab3732c2b2.png)

**Comment by mcastre** [comment]
Hi @jakehamilton i could knock this out for you.

**Comment by jakehamilton** [comment]
Hi @mcastre, sorry for the confusion. @michalStarski sent a pull request over for this ticket but GitHub wouldn't let me add them as an assignee here yet.

**Comment by mcastre** [comment]
ah no problem @jakehamilton!
