### ISSUE TITLE
Page overflow should be hidden.

### ISSUE THREAD

**Issue by jakehamilton** [jakehamilton/scrumfi.sh#2]
The page overflow breaks some styles from the app content. We should let the content be the scrolling container instead of the html page.

![image](https://user-images.githubusercontent.com/7005773/95392376-7c238880-08ad-11eb-8c5f-3410b399a851.png)

**Comment by reachtokish** [comment]
Can I work on this issue?

**Comment by jakehamilton** [comment]
Hi @reachtokish 🙌
That would be great! I see you have sent a pull request already, I'll go ahead and assign this ticket to you. Thanks so much!
