### ISSUE TITLE
Add Favicon.

### ISSUE THREAD

**Issue by jakehamilton** [jakehamilton/scrumfi.sh#3]
We should add a favicon! I'd like to use the emoji fish from this site: https://favicon.io/emoji-favicons/tropical-fish

**Comment by NLSteveO** [comment]
I can do this if you'd like to assign it to me?

**Comment by jakehamilton** [comment]
Hi @NLSteveO, that'd be great!

I'm just getting the project setup for contributions so documentation is a bit lacking at the moment. Here's some direction that may help:

You'll want to place the assets in the `frontend/public/` directory. Then, make sure that `frontend/.gitignore` does not ignore them. Once you've done that, try running the development environment and checking that your changes work correctly.

Run these commands in the root of the project to test locally:

```shell
npm install
```

```shell
npm run dev
```
